### ISSUE TITLE
Where is the code? Why still don't open source?

### ISSUE THREAD

**Issue by mei123hao** [ruirangerfan/Three-Filters-to-Normal#1]

**Comment by ruirangerfan** [comment]
Hi, thanks for your interest in our project. Unfortunately, our previous submission was rejected, and it has been currently under review by RAL (with ICRA). Hopefully, we can get some feedback/comments soon. The code will be released when the manuscript receives some positive comments.

**Comment by ruirangerfan** [comment]
> _No description provided._

Hi, thanks for your interest in our project. Unfortunately, our previous submission was rejected, and it has been currently under review by RAL (with ICRA). Hopefully, we can get some feedback/comments soon. The code will be released when the manuscript receives some positive comments.
