### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by astumpf** [ruirangerfan/Three-Filters-to-Normal#4]
Hi,

Your work looks great and I would like to test it on my machine, but I cannot compile your code:

https://github.com/ruirangerfan/Three-Filters-to-Normal/blob/903a8531b64756813b31ba9798917a501104515c/c_code/include/tftn/tftn.h#L136

```
In file included from tftn/c_code/example/demo.cpp:4:
tftn/c_code/include/tftn/tftn.h: In function ‘void TFTN_MEAN(const Vec8f&, const Vec8f&, const cv::Mat&, cv::Mat&)’:
tftn/c_code/include/tftn/tftn.h:136:37: error: conversion from ‘__m256i’ {aka ‘__vector(4) long long int’} to non-scalar type ‘Vec8i’ requested
  136 |       Vec8i number=_mm256_srli_epi32(_mm256_castps_si256(BOOL_RESULT), 31);
```

Furthermore all `isnan` calls must be called using the std namespace.

System specs:
Ubuntu 20.04.3
gcc: 9.3.0
g++: 9.3.0
cmake: 3.16.3

**Comment by bxueaa** [comment]
I find that when g++ version is larger than 7, you need to add 'std::' to compile.

**Comment by bxueaa** [comment]
There may be some differences between g++ 7.5 and g++9, maybe you can try to use static_cast to convert the type.
If I'm not busy recently, I'll fix this bug

**Comment by bxueaa** [comment]
I have update the C++ code, it is more easily to use. you can have a try.
