### ISSUE TITLE
params.txt

### ISSUE THREAD

**Issue by Ruinmou** [ruirangerfan/Three-Filters-to-Normal#5]
How do I get this file? What data is stored in it?

**Comment by bxueaa** [comment]
you can see https://github.com/ruirangerfan/Three-Filters-to-Normal/blob/master/c_code/data/android/params.txt
the first 4 number is the K of camera.
the 5th number is the number of the data. In the example, only 1 data need to be used.

**Comment by bxueaa** [comment]
I have update the C++ code, it is more easily to use. you can have a try.

**Comment by Ruinmou** [comment]
thanks!!!!
