### ISSUE TITLE
hi guys，could you please show me the specific path of 3FNE in opencv_contrib repository, thanks!

### ISSUE THREAD

**Issue by guyuezuntinggithub** [ruirangerfan/Three-Filters-to-Normal#6]

**Comment by bxueaa** [comment]
We haven't added it to opencv_contrib yet, and there are 2-3 better works being submitted and wating to be publish.
If you have any problem about 3F2N, you can email me (bxueaa@connect.ust.hk), or reply here.

**Comment by guyuezuntinggithub** [comment]
> We haven't added it to opencv_contrib yet, and there are 2-3 better works being submitted and wating to be publish. If you have any problem about 3F2N, you can email me ([bxueaa@connect.ust.hk](mailto:bxueaa@connect.ust.hk)), or reply here.

very appreciate for your reply!
I've solved it . The cuda version is easy to use!

**Comment by Mechazo11** [comment]
@guyuezuntinggithub the cuda version you used, can it be called from a C++ file?
